### ISSUE TITLE
Add harmonic analysis to `reger`

### ISSUE THREAD

**Issue by napulen** [DDMAL/key_modulation_dataset#2]
The music for the first 11 examples in Reger's book were added, but the roman numerals have not yet been included. They could be added and the metadata could be corrected in the same iteration.

**Comment by lfeistha** [comment]
What do you think of me adding the harm spine to your corpus and you adding the harm spine on my corpus ? This could allow us to check encoding and correct eventual miswritings.

**Comment by napulen** [comment]
That sounds good! Let's do that.
