### ISSUE TITLE
Raise issue in Humdrum forum regarding VerovioHumdrumViewer ignoring staff1/staff2 indications

### ISSUE THREAD

**Issue by napulen** [DDMAL/key_modulation_dataset#3]

**Comment by napulen** [comment]
Issue has been raised in the **HUG (Humdrum Users Group).

Waiting for an answer.

**Comment by napulen** [comment]
Answer has been provided. We need to add the following line somewhere in the document:

```
!!!filter: satb2gs
```

Craig also recommended to use the `autobeam` filter. I suggest we put both filters at the end of the file:

```
**kern...
...
!!!filter: satb2gs
!!!filter: autobeam
```

An important caveat though: **this `satb2gs` filter doesn't get along with the addition of other spines, for example, the `**harm` spines with the harmonic analysis**. We still need to find a workaround for that.

**Comment by napulen** [comment]
@lfeistha closing the issue but tagging you so that you become aware of this

**Comment by lfeistha** [comment]
Thank you for the information. As it seems yo be only a graphical issue (if I'm not mistaken), I suggest we don't spend too much time on the caveat.

**Comment by napulen** [comment]
I will keep looking into this as Craig proposed another solution recently.
