### ISSUE TITLE
Reger : exemples with two final keys

### ISSUE THREAD

**Issue by lfeistha** [DDMAL/key_modulation_dataset#4]
If you look at exemple 42-46 and 86-100 in Reger book, you can see that there is two goal key, a Major key and its homonym minor key in parenthesis. The only distinction between these two exemples is that the final third is either Major or minor (in parenthesis).

For these exemple should we :
- write only one file with the major key ?
- write both files, for exemple 42A.krn going to the Major key and 42B.krn going to the minor key ?

I have no preference but I think that the second is more exhaustive and don't consume too much extra time (we change only two or three words in the file).

What are your thoughts about this @napulen  ?

**Comment by napulen** [comment]
I like the second option too! I think it would be fun to see whether the algorithms provide the two goals.

**Comment by napulen** [comment]
If I run into any examples like that, I will follow your approach and encode `A-B` versions with the notes in parenthesis.
